### ISSUE TITLE
`XMLDocument` class (?)

### ISSUE THREAD

**Issue by g105b** [phpgt/dom#12]
https://developer.mozilla.org/en-US/docs/Web/API/XMLDocument

> It inherits from the generic Document and do not add any specific methods or properties to it: nevertheless, several algorithms behave differently with the two types of documents.

Shall we implement this for the sake of completeness?

**Comment by aguimaraes** [comment]
I made a mistake not referencing this issue in PR #41 .

**Comment by g105b** [comment]
Thanks, closing now.
