### ISSUE TITLE
100% test coverage

### ISSUE THREAD

**Issue by g105b** [phpgt/dom#13]
The latest commits have seriously lowered the test coverage... Need to be pretty close to 100% before v1.0.0 release.

**Comment by aguimaraes** [comment]
PHPUnit can't find any class belonging to the phpgt\dom namespace when I try to run your tests.

The path is OK in composer.json, can you help me with the possible causes of this?

**Comment by aguimaraes** [comment]
PHPUnit 5.3.2
PHP 7.0.4

**Comment by g105b** [comment]
Please run the PHP Unit supplied by Composer (`vendor/bin/phpunit`). I will look into what is causing a standalone version of PHPUnit to fail. Thanks for the report.

```
git clone https://github.com/phpgt/dom
cd dom
composer install
vendor/bin/phpunit
```

**Comment by aguimaraes** [comment]
Works using the vendor dir binary.
Must be the version difference.

```
alvaro@alvaro-pc:~/Documents/dom$ phpunit --version
PHPUnit 5.3.2 by Sebastian Bergmann and contributors.

alvaro@alvaro-pc:~/Documents/dom$ vendor/bin/phpunit --version
PHPUnit 5.1.6 by Sebastian Bergmann and contributors.
```

Thank you.
