### ISSUE TITLE
Allow null return type on NodeList::current()

### ISSUE THREAD

**Issue by g105b** [PhpGt/Dom#144]
https://github.com/PhpGt/Dom/blob/master/src/NodeList.php#L60

Null should be allowed to be returned here, as there may be no elements in the nodelist.

**Comment by Zyigh** [comment]
I would love to do that, but the way I know how to do it would mean minimum PHP version 7.1. Is that a problem ?

**Comment by Zyigh** [comment]
I would love to help on that, but the way I know how to do it implies minimum PHP version to be 7.1. Would that be ok ?

**Comment by g105b** [comment]
Thanks @Zyigh !

This library already has a dependency on at least PHP 7.1 so that's absolutely fine. You can see this in the composer.json file.

Please let me know if you have any feedback with how accessible this library was for you to contribute to - I'm very keen on improving the flow for new contributors.
