### ISSUE TITLE
HTMLCollection ArrayAccess methods

### ISSUE THREAD

**Issue by g105b** [phpgt/dom#15]
Provide array access using square brackets to the HTMLCollection class.

**Comment by aguimaraes** [comment]
Will HTMLCollection remain read only?

**Comment by g105b** [comment]
According to the specification (linked below), there should be no ability to modify an HTMLCollection or NodeList, as they are considered "live". However, I have often thought that it would be useful to be able to modify a HTMLCollection's contents...

For now, let's keep the HTMLCollection readonly, as per the spec. We can cast to an array if we need to manipulate the contents, or we can discuss making them mutable in another issue if the need comes up.

https://developer.mozilla.org/en/docs/Web/API/HTMLCollection
https://dom.spec.whatwg.org/#htmlcollection
