### ISSUE TITLE
`HTMLDocument` attributes

### ISSUE THREAD

**Issue by g105b** [phpgt/dom#22]
Missing DOM Level 2 attributes:

https://www.w3.org/TR/DOM-Level-2-HTML/html.html#ID-1689064

* [ ] URL
* [ ] anchors
* [ ] cookie
* [ ] domain
* [x] forms
* [ ] images
* [ ] links
* [ ] referrer
* [ ] title

**Comment by g105b** [comment]
I'm working on this now.

**Comment by g105b** [comment]
@j4m3s do you think I should implement `URL` and `referrer`? This seems a bit pointless when in PHP on the server... would be interested in your thoughts.

**Comment by g105b** [comment]
If you think it would be good to implement the other properties, this issue can be re-opened.

**Comment by j4m3s** [comment]
I'd be tempted to add the page-specific ones like url and referrer - so that you have a complete implementation and people can switch between php coding and javascript coding with ease.  If they're relatively straightforward I'm not sure why you wouldn't?

**Comment by g105b** [comment]
The question is, without webengine's presence, what should the value of `URL` be? Should it match the value of `$_SERVER["REQUEST_URI"]`? If so, what about in situations where a document is created manually? The document might have no significance to the actual request uri. Maybe defaulting them to null would be the answer and allow implementations to define the value.

**Comment by j4m3s** [comment]
Good point, I hadn't thought about it being created manually. Are you able
to tell?
