### ISSUE TITLE
Allow constructing from DOMDocument

### ISSUE THREAD

**Issue by g105b** [phpgt/dom#25]
Passing in a DOMDocument rather than a string of HTML would be beneficial to a project I was working on earlier this week.

**Comment by aguimaraes** [comment]
Would be wrong if I had implemented this feature on phpgt\dom\Document instead of phpgt\dom\HTMLDocument?

That way I think phpgt\dom\XMLDocument (Issue #12) could benefit too.

**Comment by g105b** [comment]
Moving your change to the `Document` class will still achieve the same implementation, and yes I agree that it will benefit issue #12 if we choose to create an XMLDocument.
