### ISSUE TITLE
Coding style

### ISSUE THREAD

**Issue by speich** [PhpGt/Dom#267]
Do you have a coding style I should use ? Is there a reason you are not using psr-2/psr-12 ? 

https://www.php-fig.org/psr/psr-12/
(Can be set directly in PhpStorm Settings ->  Editor -> Code Style -> PHP -> Set from...)

**Comment by g105b** [comment]
Yep, please see https://php.gt/styleguide

But don't worry about it. I regularly apply automated style fixes when needed, so feel free to use whatever style you like, as long as it doesn't get in the way of the diffs.

I think I will document the "I don't care what style you use" comment in more detail at some point, maybe in the contribution guidelines.

 Feedback always appreciated.
