### ISSUE TITLE
PHPUnit only runs when running vendor/bin/phpunit

### ISSUE THREAD

**Issue by g105b** [phpgt/dom#30]
Simply running `phpunit` in the directory doesn't execute any tests because it can't find the correct classes through composer.

Originaled reported in #13:

> ```
> alvaro@alvaro-pc:~/Documents/dom$ phpunit
> PHP Fatal error:  Trait 'phpgt\dom\LiveProperty' not found in /home/alvaro/Documents/dom/test/ExampleLiveProperty.php on line 5
>```

**Comment by aguimaraes** [comment]
If I may be so bold, would you consider upgrading to phpunit 5.3?

**Comment by g105b** [comment]
The reason PHPUnit is on the particular version currently is because there was a problem resolving packages through composer when PHP 7.0 was new - these issues showed up in the CI test runner - I think these issues will be sorted now, so I'll look into upgrading to the latest version.
