### ISSUE TITLE
LIBXML_COMPACT

### ISSUE THREAD

**Issue by g105b** [phpgt/dom#38]
Have a look into whether this actually speeds anything up: http://php.net/manual/en/libxml.constants.php

> LIBXML_COMPACT (integer)
> Activate small nodes allocation optimization. This may speed up your application without needing to change the code

**Comment by ccharlton** [comment]
Any update about this?

**Comment by g105b** [comment]
Hi @ccharlton 

Please see https://gist.github.com/g105b/7ecb3a910fc241bcbb933900a409afbe for a test I made. I'm not sure under what condition LIBXML_COMPACT should make any difference, but the test doesn't show any conclusive evidence to have any influence over processing time.

The test script creates a DOM tree of 100,000 elements, attached at random to each other. Then to test the parser, it is serialised to HTML and a new document is created with the provided HTML. This is then serialised to STDOUT and the whole process is timed.

I'm going to look into what the purpose of LIBXML_COMPACT is, but for now I'm going to close this issue as your comment triggered me to investigate whether it makes any significant difference to worry about.
