### ISSUE TITLE
Can't user this anymore on PHP 7.4?

### ISSUE THREAD

**Issue by JKwang00** [PhpGt/Dom#408]
HI :)
i'm using PHP 7.4
how can i use this library on PHP 7.4??
or not support 7.4 anymore??
thank you!

**Comment by g105b** [comment]
Hi, I'm afraid not. PHP 7.4 isn't officially supported by PHP any more (see https://www.php.net/supported-versions.php)

I would love to support older versions, but it was too much effort to back port the functionality to 7.4 so I opted against it.

The good news is that PHP is really easy to upgrade, with very few backwards breaking changes. If you need any assistance I'll happily help out if it means another happy developer using PhpGt :)

**Comment by JKwang00** [comment]
Thank you for answer.
I worry about website is not stable when i upgrade to PHP 8
So i can't decide to upgrade PHP 8 on my website.
However I really want to use this library. this is so good.

have a nice day :)

**Comment by JKwang00** [comment]
Thank you for answer.
I worry about website is not stable when i upgrade to PHP 8
So i can't decide to upgrade PHP 8 on my website.
However I really want to use this library. this is so good.

have a nice day :)

**Comment by g105b** [comment]
I would recommend running the code locally on your computer so you can experiment with changing the PHP version, without it affecting the live website.

I hope it works out for you and you can start using this library.

Have a nice day too.
