### ISSUE TITLE
Test that adding HTML strings to textContent does not affect the child elements.

### ISSUE THREAD

**Issue by g105b** [PhpGt/Dom#51]
`$element->textContent = "<p>Test</p>";`

The above example should **not** create a paragraph element as a child of the element. It should escape the content correctly, displaying the chevrons to the browser.

This is due to the difference between textContent and innerHTML. The latter sets literal html within the element whereas textContent should escape any HTML strings. Hopefully this is handled by the native DOMDocument but tests are needed to make sure.

**Comment by lcrossan** [comment]
Hey, I'd like to tackle this. Would you be able to point me to the code that would effect this?

**Comment by g105b** [comment]
Sure, let me provide you with some background.

The [`textContent`][mdn-textContent] property is implemented by the native [`DOMNode`][php-domnode] class, part of PHP's [DOMDocument][php-domdocument].

As the name suggests, the `textContent` property is a string representation of the **text** content of the Node and its decendant children. This property differs from the [`innerHTML`][mdn-innerHTML] property as innerHTML returns the HTML as its name indicates. Quite often, in order to retrieve or write text within an element, people use innerHTML. `textContent` should be used instead. Because the text is not parsed as HTML, it's likely to have better performance. Moreover, this avoids an XSS attack vector.

When setting the `textContent` of a node to something like `"<p>Test</p>"`, it should not create a paragraph child element. Instead, the string should be escaped (or in fact, [HTML-encoded][php-htmlentities]). The true content of the node, after setting the above textContent, would be something along the lines of `&lt;p&gt;Test&lt;/p&gt;`.

## Writing tests.

The behaviour we are testing is on the `DOMNode` class, which PHP.Gt's DOM class extends into `phpgt\dom\Node`, so we should first create a unit test script in `test/Node.test.php`. See below for an example empty test class:

```php
<?php
namespace phpgt\dom;

class NodeTest extends \PHPUnit_Framework_TestCase {

public function testSomething() {
    $this->assertTrue(true);
}

}#
```

What the test should do:

1. Create a new Document using the test HTML provided in `test/Helper.php.
2. Reference (or create) a Node within the document.
3. Add a string of HTML to the Node's textContent property.
4. Assert that the Node has not had any child element nodes created.

Further tests on the Node class should show that Nodes with child elements have their text content available in the parent Node's textContent property, as described in the [MDN documentation of textContent][mdn-textContent].

Let me know if you need any more help.

[mdn-textContent]: https://developer.mozilla.org/en/docs/Web/API/Node/textContent
[php-domnode]: http://php.net/manual/en/class.domnode.php
[php-domdocument]: http://php.net/manual/en/class.domdocument.php
[mdn-innerHTML]: https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML
[php-htmlentities]: http://php.net/manual/en/function.htmlentities.php
