### ISSUE TITLE
Implement \Psr\Http\Message\StreamInterface

### ISSUE THREAD

**Issue by j4m3s** [PhpGt/Dom#58]
Would be very useful to either implement StreamInterface or provide a method that gets one, to allow `HTMLDocument`s to be used easily with PSR7 `ResponseInterface`s.

**Comment by g105b** [comment]
I've just been going through marking issues as out-of-scope if they are not part of the DOM standard. Do you think this feature can be implemented without adding unexpected features to DOM?

**Comment by j4m3s** [comment]
It's not dom standard by any means so not a v1.0 feature.  I don't think it would require anything confusing, but would mean adding a method that isn't present on the DOM standard (although there are already others of these on Dom aren't there?).  I see PSR7 gaining more and more ground, so people will be implementing this function themselves if it's not part of the library.

I've just been thinking that it might be a good idea to implement the `__toString()` as an alias for `saveHTML()` (which I think is an awful name for that function in php's DOMDocument).  Implementing `__toString()` would allow users to simply cast to a string - or echo it etc.

**Comment by g105b** [comment]
Agreed. This will remain as a 2.0 issue as I can see many benefits without breaking any compatibility with standards.
