### ISSUE TITLE
Querying an HTMLDocument constructed with an empty string is Fatal

### ISSUE THREAD

**Issue by j4m3s** [PhpGt/Dom#62]
It's clearly my fault for creating the HTMLDocument with an empty string, but it might be defensive to do an is_null check on the documentElement before attempting to access it.  Given an empty HTMLDocument you might expect a querySelector call for anything to successfully return nothing rather than cause a fatal error.

```
$domDoc = new \phpgt\dom\HTMLDocument("");
$domDoc->querySelector("div");

PHP Fatal error:  Uncaught Error: Call to a member function querySelector() on null in phpgt/dom/src/HTMLDocument.php:35
```

**Comment by g105b** [comment]
This should mimic what happens in the browser when creating a new document. The HTML, HEAD and BODY elements are inferred and created empty if nothing is supplied.
