### ISSUE TITLE
Class implementation: DocumentFragment.

### ISSUE THREAD

**Issue by g105b** [PhpGt/Dom#67]
+ [x] children
+ [x] firstElementChild
+ [x] lastElementChild
+ [x] childElementCount
+ [x] ~~querySelector~~
+ [x] ~~querySelectorAll~~
+ [x] getElementById

**Comment by g105b** [comment]
See tests in branch [fragment](https://github.com/PhpGt/Dom/tree/fragment)

**Comment by g105b** [comment]
Looks like querySelector(All) methods should actually be part of the `ParentNode` trait.

https://developer.mozilla.org/en-US/docs/Web/API/ParentNode

**Comment by j4m3s** [comment]
Have added some additional tests to my fork of that branch, to make sure the scope of queries to the fragment is limited to the fragment itself and not the document it's appended-to.
